### ISSUE TITLE
I can't run it after clone

### ISSUE THREAD

**Issue by edilyxin** [semlanik/QtTWAIN#1]
hi  guy：
      I learned a lot from reading your code, so I tried copying it and running it locally.But I ran into some minor problems.It doesn't work in my QTCreator IDE(version 4.14)（QT version 5.12）. The error message is as follows:
**

> “D:\qtp\QtTWAIN\examples\CMakeLists.txt:8: error: Could not find a package configuration file provided by "QtTWAINProject" with any of the following names: QtTWAINProjectConfig.cmake qttwainproject-config.cmake Add the installation prefix of "QtTWAINProject" to CMAKE_PREFIX_PATH or set "QtTWAINProject_DIR" to a directory containing one of the above files.  If "QtTWAINProject" provides a separate development package or SDK, be sure it has been installed."

**
I am a C ++ novice, but I am interested in Twain programming. I hope I can get your help. Thank you!

**Comment by semlanik** [comment]
Hi, sorry it was a mistake that I made while porting the project to the CMake build procedure. Hope it works now.

**Comment by Okada-Hideki** [comment]
Hello.
When I tried to compile the source code, the compiler got mad at me for not having qtwainglobal.h.
Is the file name qttwainglobal.h the corresponding file?
I would like you to change the file name if possible, can you please do so?
When I try to change the file name with CMake, an error occurs and the work stops, so thank you for your understanding.
